# Generated by Django 6.1.1 on 2026-09-08 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kie_api_key_encrypted', models.TextField(blank=True, default='')),
                ('telegram_bot_token_encrypted', models.TextField(blank=True, default='')),
                ('telegram_chat_id', models.CharField(blank=True, default='', max_length=64)),
                ('telegram_notifications_enabled', models.BooleanField(default=True)),
                ('default_chat_model', models.CharField(blank=True, default='', max_length=200)),
                ('default_image_model', models.CharField(blank=True, default='', max_length=200)),
                ('default_video_model', models.CharField(blank=True, default='', max_length=200)),
                ('default_music_model', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user settings',
                'verbose_name_plural': 'user settings',
            },
        ),
    ]
