# Generated by Django 6.1.1 on 2026-09-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersettings_browser_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='telegram_bot_username',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
