# Generated by Django 6.1.1 on 2026-09-08 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('music', 'Music')], max_length=16)),
                ('model_slug', models.CharField(max_length=200)),
                ('model_id', models.CharField(blank=True, default='', max_length=200)),
                ('model_name', models.CharField(blank=True, default='', max_length=200)),
                ('adapter', models.CharField(default='jobs', max_length=32)),
                ('prompt', models.TextField(blank=True, default='')),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('reference_images', models.JSONField(blank=True, default=list)),
                ('task_id', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='image', max_length=16)),
                ('file', models.FileField(blank=True, upload_to='generations/%Y/%m/')),
                ('remote_url', models.URLField(blank=True, default='', max_length=1000)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1000)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='generation.generation')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['user', 'category', '-created_at'], name='generation__user_id_409471_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['status'], name='generation__status_0d9af0_idx'),
        ),
    ]
