# Generated by Django 6.1.1 on 2026-09-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='poll_path',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
